// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "documento-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/view-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>
#include <odb/pgsql/view-result.hxx>

namespace odb
{
  // Documento
  //

  const char access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  persist_statement_name[] = "Entidades_Documento_persist";

  const char access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  find_statement_name[] = "Entidades_Documento_find";

  const char access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  update_statement_name[] = "Entidades_Documento_update";

  const char access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  erase_statement_name[] = "Entidades_Documento_erase";

  const char access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  query_statement_name[] = "Entidades_Documento_query";

  const char access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  erase_query_statement_name[] = "Entidades_Documento_erase_query";

  const unsigned int access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::timestamp_oid,
    pgsql::int2_oid,
    pgsql::bytea_oid
  };

  const unsigned int access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::timestamp_oid,
    pgsql::int2_oid,
    pgsql::bytea_oid,
    pgsql::int8_oid
  };

  struct access::object_traits_impl< ::Entidades::Documento, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::Entidades::Documento, id_pgsql >::id_type
  access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          ::qlonglong,
          pgsql::id_bigint >::set_value (
        id,
        i.m_codigo_value,
        i.m_codigo_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // m_codigo
    //
    t[0UL] = 0;

    // m_nome
    //
    if (t[1UL])
    {
      i.m_nome_value.capacity (i.m_nome_size);
      grew = true;
    }

    // m_descricao
    //
    if (t[2UL])
    {
      i.m_descricao_value.capacity (i.m_descricao_size);
      grew = true;
    }

    // m_ultimaAlteracao
    //
    t[3UL] = 0;

    // m_versao
    //
    t[4UL] = 0;

    // m_arquivo
    //
    if (t[5UL])
    {
      i.m_arquivo_value.capacity (i.m_arquivo_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // m_codigo
    //
    if (sk != statement_insert && sk != statement_update)
    {
      b[n].type = pgsql::bind::bigint;
      b[n].buffer = &i.m_codigo_value;
      b[n].is_null = &i.m_codigo_null;
      n++;
    }

    // m_nome
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.m_nome_value.data ();
    b[n].capacity = i.m_nome_value.capacity ();
    b[n].size = &i.m_nome_size;
    b[n].is_null = &i.m_nome_null;
    n++;

    // m_descricao
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.m_descricao_value.data ();
    b[n].capacity = i.m_descricao_value.capacity ();
    b[n].size = &i.m_descricao_size;
    b[n].is_null = &i.m_descricao_null;
    n++;

    // m_ultimaAlteracao
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.m_ultimaAlteracao_value;
    b[n].is_null = &i.m_ultimaAlteracao_null;
    n++;

    // m_versao
    //
    b[n].type = pgsql::bind::smallint;
    b[n].buffer = &i.m_versao_value;
    b[n].is_null = &i.m_versao_null;
    n++;

    // m_arquivo
    //
    b[n].type = pgsql::bind::bytea;
    b[n].buffer = i.m_arquivo_value.data ();
    b[n].capacity = i.m_arquivo_value.capacity ();
    b[n].size = &i.m_arquivo_size;
    b[n].is_null = &i.m_arquivo_null;
    n++;
  }

  void access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // m_nome
    //
    {
      ::QString const& v =
        o.nome ();

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.m_nome_value.capacity ());
      pgsql::value_traits<
          ::QString,
          pgsql::id_string >::set_image (
        i.m_nome_value,
        size,
        is_null,
        v);
      i.m_nome_null = is_null;
      i.m_nome_size = size;
      grew = grew || (cap != i.m_nome_value.capacity ());
    }

    // m_descricao
    //
    {
      ::QString const& v =
        o.descricao ();

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.m_descricao_value.capacity ());
      pgsql::value_traits<
          ::QString,
          pgsql::id_string >::set_image (
        i.m_descricao_value,
        size,
        is_null,
        v);
      i.m_descricao_null = is_null;
      i.m_descricao_size = size;
      grew = grew || (cap != i.m_descricao_value.capacity ());
    }

    // m_ultimaAlteracao
    //
    {
      ::QDateTime const& v =
        o.ultimaAlteracao ();

      bool is_null (false);
      pgsql::value_traits<
          ::QDateTime,
          pgsql::id_timestamp >::set_image (
        i.m_ultimaAlteracao_value, is_null, v);
      i.m_ultimaAlteracao_null = is_null;
    }

    // m_versao
    //
    {
      ::quint16 const& v =
        o.versao ();

      bool is_null (false);
      pgsql::value_traits<
          ::quint16,
          pgsql::id_smallint >::set_image (
        i.m_versao_value, is_null, v);
      i.m_versao_null = is_null;
    }

    // m_arquivo
    //
    {
      ::QByteArray const& v =
        o.arquivo ();

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.m_arquivo_value.capacity ());
      pgsql::value_traits<
          ::QByteArray,
          pgsql::id_bytea >::set_image (
        i.m_arquivo_value,
        size,
        is_null,
        v);
      i.m_arquivo_null = is_null;
      i.m_arquivo_size = size;
      grew = grew || (cap != i.m_arquivo_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // m_codigo
    //
    {
      ::qlonglong v;

      pgsql::value_traits<
          ::qlonglong,
          pgsql::id_bigint >::set_value (
        v,
        i.m_codigo_value,
        i.m_codigo_null);

      o.setCodigo (v);
    }

    // m_nome
    //
    {
      ::QString v;

      pgsql::value_traits<
          ::QString,
          pgsql::id_string >::set_value (
        v,
        i.m_nome_value,
        i.m_nome_size,
        i.m_nome_null);

      o.setNome (v);
    }

    // m_descricao
    //
    {
      ::QString v;

      pgsql::value_traits<
          ::QString,
          pgsql::id_string >::set_value (
        v,
        i.m_descricao_value,
        i.m_descricao_size,
        i.m_descricao_null);

      o.setDescricao (v);
    }

    // m_ultimaAlteracao
    //
    {
      ::QDateTime v;

      pgsql::value_traits<
          ::QDateTime,
          pgsql::id_timestamp >::set_value (
        v,
        i.m_ultimaAlteracao_value,
        i.m_ultimaAlteracao_null);

      o.setUltimaAlteracao (v);
    }

    // m_versao
    //
    {
      ::quint16 v;

      pgsql::value_traits<
          ::quint16,
          pgsql::id_smallint >::set_value (
        v,
        i.m_versao_value,
        i.m_versao_null);

      o.setVersao (v);
    }

    // m_arquivo
    //
    {
      ::QByteArray v;

      pgsql::value_traits<
          ::QByteArray,
          pgsql::id_bytea >::set_value (
        v,
        i.m_arquivo_value,
        i.m_arquivo_size,
        i.m_arquivo_null);

      o.setArquivo (v);
    }
  }

  void access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      pgsql::value_traits<
          ::qlonglong,
          pgsql::id_bigint >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::Entidades::Documento, id_pgsql >::persist_statement[] =
  "INSERT INTO \"t_documento\" "
  "(\"c_codigo\", "
  "\"c_nome\", "
  "\"c_descricao\", "
  "\"c_ultimaalteracao\", "
  "\"c_versao\", "
  "\"c_arquivo\") "
  "VALUES "
  "(DEFAULT, $1, $2, $3, $4, $5) "
  "RETURNING \"c_codigo\"";

  const char access::object_traits_impl< ::Entidades::Documento, id_pgsql >::find_statement[] =
  "SELECT "
  "\"t_documento\".\"c_codigo\", "
  "\"t_documento\".\"c_nome\", "
  "\"t_documento\".\"c_descricao\", "
  "\"t_documento\".\"c_ultimaalteracao\", "
  "\"t_documento\".\"c_versao\", "
  "\"t_documento\".\"c_arquivo\" "
  "FROM \"t_documento\" "
  "WHERE \"t_documento\".\"c_codigo\"=$1";

  const char access::object_traits_impl< ::Entidades::Documento, id_pgsql >::update_statement[] =
  "UPDATE \"t_documento\" "
  "SET "
  "\"c_nome\"=$1, "
  "\"c_descricao\"=$2, "
  "\"c_ultimaalteracao\"=$3, "
  "\"c_versao\"=$4, "
  "\"c_arquivo\"=$5 "
  "WHERE \"c_codigo\"=$6";

  const char access::object_traits_impl< ::Entidades::Documento, id_pgsql >::erase_statement[] =
  "DELETE FROM \"t_documento\" "
  "WHERE \"c_codigo\"=$1";

  const char access::object_traits_impl< ::Entidades::Documento, id_pgsql >::query_statement[] =
  "SELECT "
  "\"t_documento\".\"c_codigo\", "
  "\"t_documento\".\"c_nome\", "
  "\"t_documento\".\"c_descricao\", "
  "\"t_documento\".\"c_ultimaalteracao\", "
  "\"t_documento\".\"c_versao\", "
  "\"t_documento\".\"c_arquivo\" "
  "FROM \"t_documento\"";

  const char access::object_traits_impl< ::Entidades::Documento, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"t_documento\"";

  const char access::object_traits_impl< ::Entidades::Documento, id_pgsql >::table_name[] =
  "\"t_documento\"";

  void access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.setCodigo (static_cast< id_type > (st.id ()));

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.codigo ());
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    ODB_POTENTIALLY_UNUSED (db);

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::Entidades::Documento, id_pgsql >::pointer_type
  access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.codigo ());

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::Entidades::Documento, id_pgsql >::object_type >
  access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::Entidades::Documento, id_pgsql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }

  // DocumentoInfo
  //

  const char access::view_traits_impl< ::Entidades::DocumentoInfo, id_pgsql >::
  query_statement_name[] = "Entidades_DocumentoInfo_query";

  bool access::view_traits_impl< ::Entidades::DocumentoInfo, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // quantidade
    //
    t[0UL] = 0;

    return grew;
  }

  void access::view_traits_impl< ::Entidades::DocumentoInfo, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i)
  {
    using namespace pgsql;

    pgsql::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // quantidade
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.quantidade_value;
    b[n].is_null = &i.quantidade_null;
    n++;
  }

  void access::view_traits_impl< ::Entidades::DocumentoInfo, id_pgsql >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // quantidade
    //
    {
      ::std::size_t& v =
        o.quantidade;

      pgsql::value_traits<
          ::std::size_t,
          pgsql::id_bigint >::set_value (
        v,
        i.quantidade_value,
        i.quantidade_null);
    }
  }

  access::view_traits_impl< ::Entidades::DocumentoInfo, id_pgsql >::query_base_type
  access::view_traits_impl< ::Entidades::DocumentoInfo, id_pgsql >::
  query_statement (const query_base_type& q)
  {
    query_base_type r (
      "SELECT "
      "count(\"t_documento\".\"c_codigo\") ");

    r += "FROM \"t_documento\"";

    if (!q.empty ())
    {
      r += " ";
      r += q.clause_prefix ();
      r += q;
    }

    return r;
  }

  result< access::view_traits_impl< ::Entidades::DocumentoInfo, id_pgsql >::view_type >
  access::view_traits_impl< ::Entidades::DocumentoInfo, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (query_statement (q));
    qs.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        qs.clause (),
        false,
        true,
        qs.parameter_types (),
        qs.parameter_count (),
        qs.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::view_result_impl<view_type> > r (
      new (shared) pgsql::view_result_impl<view_type> (
        qs, st, sts, 0));

    return result<view_type> (r);
  }

  // DocumentoView
  //

  const char access::view_traits_impl< ::Entidades::DocumentoView, id_pgsql >::
  query_statement_name[] = "Entidades_DocumentoView_query";

  bool access::view_traits_impl< ::Entidades::DocumentoView, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // codigo
    //
    t[0UL] = 0;

    // nome
    //
    if (t[1UL])
    {
      i.nome_value.capacity (i.nome_size);
      grew = true;
    }

    // descricao
    //
    if (t[2UL])
    {
      i.descricao_value.capacity (i.descricao_size);
      grew = true;
    }

    // ultimaAlteracao
    //
    t[3UL] = 0;

    // versao
    //
    t[4UL] = 0;

    return grew;
  }

  void access::view_traits_impl< ::Entidades::DocumentoView, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i)
  {
    using namespace pgsql;

    pgsql::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // codigo
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.codigo_value;
    b[n].is_null = &i.codigo_null;
    n++;

    // nome
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.nome_value.data ();
    b[n].capacity = i.nome_value.capacity ();
    b[n].size = &i.nome_size;
    b[n].is_null = &i.nome_null;
    n++;

    // descricao
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.descricao_value.data ();
    b[n].capacity = i.descricao_value.capacity ();
    b[n].size = &i.descricao_size;
    b[n].is_null = &i.descricao_null;
    n++;

    // ultimaAlteracao
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.ultimaAlteracao_value;
    b[n].is_null = &i.ultimaAlteracao_null;
    n++;

    // versao
    //
    b[n].type = pgsql::bind::smallint;
    b[n].buffer = &i.versao_value;
    b[n].is_null = &i.versao_null;
    n++;
  }

  void access::view_traits_impl< ::Entidades::DocumentoView, id_pgsql >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // codigo
    //
    {
      ::qlonglong& v =
        o.codigo;

      pgsql::value_traits<
          ::qlonglong,
          pgsql::id_bigint >::set_value (
        v,
        i.codigo_value,
        i.codigo_null);
    }

    // nome
    //
    {
      ::QString& v =
        o.nome;

      pgsql::value_traits<
          ::QString,
          pgsql::id_string >::set_value (
        v,
        i.nome_value,
        i.nome_size,
        i.nome_null);
    }

    // descricao
    //
    {
      ::QString& v =
        o.descricao;

      pgsql::value_traits<
          ::QString,
          pgsql::id_string >::set_value (
        v,
        i.descricao_value,
        i.descricao_size,
        i.descricao_null);
    }

    // ultimaAlteracao
    //
    {
      ::QDateTime& v =
        o.ultimaAlteracao;

      pgsql::value_traits<
          ::QDateTime,
          pgsql::id_timestamp >::set_value (
        v,
        i.ultimaAlteracao_value,
        i.ultimaAlteracao_null);
    }

    // versao
    //
    {
      ::quint16& v =
        o.versao;

      pgsql::value_traits<
          ::quint16,
          pgsql::id_smallint >::set_value (
        v,
        i.versao_value,
        i.versao_null);
    }
  }

  access::view_traits_impl< ::Entidades::DocumentoView, id_pgsql >::query_base_type
  access::view_traits_impl< ::Entidades::DocumentoView, id_pgsql >::
  query_statement (const query_base_type& q)
  {
    query_base_type r (
      "SELECT "
      "\"t_documento\".\"c_codigo\", "
      "\"t_documento\".\"c_nome\", "
      "\"t_documento\".\"c_descricao\", "
      "\"t_documento\".\"c_ultimaalteracao\", "
      "\"t_documento\".\"c_versao\" ");

    r += "FROM \"t_documento\"";

    if (!q.empty ())
    {
      r += " ";
      r += q.clause_prefix ();
      r += q;
    }

    return r;
  }

  result< access::view_traits_impl< ::Entidades::DocumentoView, id_pgsql >::view_type >
  access::view_traits_impl< ::Entidades::DocumentoView, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (query_statement (q));
    qs.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        qs.clause (),
        false,
        true,
        qs.parameter_types (),
        qs.parameter_count (),
        qs.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::view_result_impl<view_type> > r (
      new (shared) pgsql::view_result_impl<view_type> (
        qs, st, sts, 0));

    return result<view_type> (r);
  }
}

#include <odb/post.hxx>
